### ISSUE TITLE
netdata自动安装后，访问网页提示没有全效

### ISSUE THREAD

**Issue by iWishingStar** [xzhih/ONMP#10]
提示没有权限访问 /opt/share/netdata/web

**Comment by iWishingStar** [comment]
给权限没用，不管是root还是nobody，都没用

**Comment by xzhih** [comment]
给目录个777

**Comment by xzhih** [comment]
chmod -R 777 /opt/share/netdata/web

**Comment by iWishingStar** [comment]
权限相关的指令都用过了的，你给的改变文件夹为777也没用，上一级netdata都改成777了，也没用

**Comment by iWishingStar** [comment]
access to file is not permitted : /opt/share/netdata/web/

**Comment by xzhih** [comment]
这我就不晓得了，不用这东西吧，没啥用
