### ISSUE TITLE
 Unknown package 'mariadb-client-extra'.

### ISSUE THREAD

**Issue by andyhuai** [xzhih/ONMP#12]
Unknown package 'mariadb-client-extra'.
Collected errors:
* opkg_install_cmd: Cannot install package mariadb-client-extra.

还是这个问题。没有办法，
我看官方源里面就没有这个包啊，7620和7621里面都没有这个包，想手动安装都不行

**Comment by lvxj11** [comment]
root@XiaoQiang:~# opkg find mariadb*
mariadb-client - 5.5.58-1 - MariaDB Server client applications
mariadb-client-extra - 5.5.58-1 - MariaDB Server additional client applications
mariadb-server - 5.5.58-1 - MariaDB Server server

我这是有的，使用`opkg find mariadb*`命令搜索可安装包。之前最好执行`opkg update`。
如果还是没有请检查entware版本和源。

**Comment by andyhuai** [comment]
@lvxj11 

Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for mariadb-client-extra found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package mariadb-client-extra.

我手动安装，报这个错。

**Comment by andyhuai** [comment]
arch all 1
arch ralink 200
arch ramips_24kec 100

这个我在软件包配置里面加了

**Comment by andyhuai** [comment]
另外，我只想装可道云，数据库我觉得可以跳过去不安装

**Comment by lvxj11** [comment]
这个onmp是适配entwart的，你需要确认一下安装的entwart是否适配你的cpu和固件。

可道云的确不用数据库，根据我的试用比nextcloud和owncloud都流畅的多，各项功能更像是一个商业版软件比nextcloud好用简单。只是不能挂载外部存储，免费版有限制，只能建立 5个用户等。
你可以编辑安装脚本跳过试试看。做好备份，大不了恢复重来。现在的设备小心点一般是搞不死的。

**Comment by xzhih** [comment]
只需要可道云的话，手动装就行，很简单的，装好 `nginx` 和 `php`，自己配置一下就可以了

**Comment by xzhih** [comment]
看log啊，开哪里报错了，装上了就不难解决的，就是个配置文件的问题

**Comment by lvxj11** [comment]
如果你装的nginx可以尝试卸载后安装nginx-extras，我之前安装nginx也是怎么也启动不了，换了nginx-extras就好了。

**Comment by xzhih** [comment]
你这。。。人家是 php7，给装个 php5 的 mod，能成功吗。。。。

按步骤来，装 entware，再装 nginx，PHP

**Comment by andyhuai** [comment]
@xzhih 我装的就是php5，没有装php7，肯定是php-mod-json，都是配套的，并没有问题

**Comment by longalong** [comment]
admin@RT-AC3100:/tmp/opt#  * opkg_install_cmd: Cannot install package mariadb-server-extra.
-sh: bcloud: not found
admin@RT-AC3100:/tmp/opt# mariadb-client
-sh: mariadb-client: not found
admin@RT-AC3100:/tmp/opt# mariadb-client-extra
-sh: mariadb-client-extra: not found
admin@RT-AC3100:/tmp/opt# /opt/VPN
-sh: 可能会因为某些问题某些核心软件包无法安装，请保持/opt/目录足够干净，如果是网络问题，请挂全局VPN再次运行命令: not found
admin@RT-AC3100:/tmp/opt# admin@RT-AC3100:/tmp/opt# opkg find mariadb
-sh: admin@RT-AC3100:/tmp/opt#: not found
admin@RT-AC3100:/tmp/opt# admin@RT-AC3100:/tmp/opt# # opkg find mariadb*
-sh: admin@RT-AC3100:/tmp/opt#: not fo

我也遇到这个问题了

**Comment by xzhih** [comment]
装好 entware 了吗，使用的源要是最新的  http://bin.entware.net

**Comment by longalong** [comment]
> http://bin.entware.net

谢谢回答，替换过后，提示has no valid architecture，我的是K3，刷的梅林7.8，选择的是armv7 2.6，奇怪

**Comment by xzhih** [comment]
@longalong 
你是怎么替换的

**Comment by longalong** [comment]
> @longalong
> 你是怎么替换的

src/gz packages http://pkg.entware.net/binaries/armv7
dest root /
dest ram /opt/tmp
lists_dir ext /opt/var/opkg-lists
option tmp_dir /opt/tmp
直接在opkg.conf替换之前的http://pkg.entware.net/binaries/armv7

**Comment by xzhih** [comment]
@longalong 
你怕不是在搞笑哦，教程说得清清楚楚，第一步就是安装 entware，还这样乱来，我是醉了

![a](https://i.loli.net/2019/01/06/5c31d58ba3b28.png)

**Comment by longalong** [comment]
> @longalong
> 你怕不是在搞笑哦，教程说得清清楚楚，第一步就是安装 entware，还这样乱来，我是醉了
> 
> ![a](https://camo.githubusercontent.com/9b20bbbdfea565d64e7523039e46ed1aa8cc427d/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30312f30362f356333316435386261336232382e706e67)
当然是先装entware这个环境，跑的zerotier就在这个环境下跑的。在winscp进入路由后，更改过源后，提示错误invalide architecture。后面，我索性全部清空，改源后。重启，重新安装entware 环境，重新走命令，然后就全部走通了。应该是更换过源后，要重启一次。谢谢
