### ISSUE TITLE
脚本运行出错~

### ISSUE THREAD

**Issue by fzhw88** [xzhih/ONMP#15]
curl: (7) Failed to connect to 192.168.4.237 port 4000: Connection timed out
、看了下脚本，
    curl -kfsSL http://192.168.4.237:4000/onmp.sh > /opt/onmp/onmp.sh
这个ip地址被写死在这里了，不知道什么情况？

按照分步操作确实可以安装了，不过到最后提示PHP-FPM 启动失败，运行php-fpm命令会收到一下错误提示：
[01-May-2018 05:29:19] ERROR: failed to open configuration file '/opt/etc/php-fpm.conf': No such file or directory (2)
[01-May-2018 05:29:19] ERROR: failed to load configuration file '/opt/etc/php-fpm.conf'
[01-May-2018 05:29:19] ERROR: FPM initialization failed

环境是A3004NS，灯大的最新内测固件，usb磁盘是ext4格式。

另外教程中其实有一处有问题，padavan安装entware的标准流程应该是格式化-新建opt-ejusb卸载usb（或者网页端安全弹出）-打开entware-拔掉usb再插上，就会自动安装了，如果是按照教程写的重启安装，我尝试过很多次结果都是失败，提示缺少文件。参考：https://bitbucket.org/padavan/rt-n56u/wiki/EN/HowToConfigureEntware

Thx~节日愉快！

**Comment by xzhih** [comment]
第一个问题：我昨晚更新的时候，把本地测试的给上传了，现在更新了。不好意思哈

第二个问题：PHP 配置文件找不到，可以尝试初始化一次。

第三个问题：我写那个教程没问题的，在你之前的人都成功了，开启 entware 后在开机的时候会挂载 /opt，只要 /opt 挂载成功，会自动执行 opkg.sh，这个操作和你拔插 U 盘是一个道理，之所以我写重启，是因为有些 padavan 的自动挂载功能不行，拔插不会挂载 /opt。
