### ISSUE TITLE
梅林7.8安装所碰到的问题

### ISSUE THREAD

**Issue by engine-we** [xzhih/ONMP#19]
1.opkg 源地址http://pkg.entware.net/binaries/armv7/  Packages.gz 包源列表未更新导致opkg update 无效
2.ONMP 安装软件包列表 packages 的包源 mariadb-server-extra 已经 被改成mariadb-server 导致安装中断

暂时解决
1.重新打包 http://pkg.entware.net/binaries/armv7/Packages 为 gz 重名 packages 覆盖至 /var/opkg-lists/packages
2.onmp.sh mariadb-server-extra 换成 mariadb-server 去掉 opkg update 命令

最后
onmp正在启动
Nginx 启动成功
PHP-FPM 启动失败
MySQL 启动成功
onmp启动失败

不知为何

**Comment by xzhih** [comment]
1. opkg update 无效这个应该是你的固件没有同步entware源的更改，最近entware对源做了一些改动

2. php启动失败一般是运行用户不正确或内存不足，使用 'php-fpm --fpm-config /opt/etc/php7-fpm.conf' 命令查看具体原因，一般情况下 PHP 不能使用 root 用户运行，可能需要新建用户，不过梅林似乎不会有这个问题，内存不足就开启虚拟内存 swap

**Comment by engine-we** [comment]
谢谢 php 启动失败的已经解决，之前梅林安装的软件虚拟内存卸掉 onmp创建swap就好了，但现在访问地址   出现 502 Bad Gateway

**Comment by xzhih** [comment]
执行一次 onmp 里的全部重置
