### ISSUE TITLE
Nextcloud Internal Server Error

### ISSUE THREAD

**Issue by wongthinker** [xzhih/ONMP#2]
nextcloud安装好，配置完数据库后就出现这个了~~

> Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request.
> Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
> More details can be found in the server log.

**Comment by xzhih** [comment]
什么机器？什么配置？nextcloud装不了就装owncloud试试，nextcloud消耗资源比较大，只建议软路由安装

**Comment by wongthinker** [comment]
斐讯K3+LEDE v2.5 By stones

**Comment by wongthinker** [comment]
试了oc可以用。但是想用nc啊，毕竟oc已经弃坑了啊

**Comment by xzhih** [comment]
新版oc装上插件之后不比nc差，并且目前在entware环境上装nc，问题非常多（比如无法上传文件，时间长了会崩溃），不是很稳定

**Comment by wongthinker** [comment]
那么就用oc吧，nc删除就wwwroot下目录删除就ok了吧？

**Comment by xzhih** [comment]
删除wwwroot下的目录，还有/opt/etc/nginx/vhost/里面的同名目录
