### ISSUE TITLE
nginx 启动失败 貌似是用户问题

### ISSUE THREAD

**Issue by icksky** [xzhih/ONMP#20]
```
nginx: [emerg] getpwnam("admin") failed (2: No such file or directory) in /opt/etc/nginx/nginx.conf:1
```
但是我看用户表里面有`admin`这个用户的。
而且用onmp 启动的话 会告知nginx启动成功 实际并没有
求助。。
PS： 梅林系统

**Comment by xzhih** [comment]
梅林改nginx的运行用户和用户组为admin试试，在 `/opt/etc/nginx/nginx.conf` 的第一行

**Comment by icksky** [comment]
@xzhih 我改成 user admin admin; 还是这个错误。

**Comment by xzhih** [comment]
你用的是哪个用户名

**Comment by icksky** [comment]
@xzhih 我登录的就是admin。之前是可以跑的。这两天不知道哪里出问题了。。。就跑不起来了

**Comment by xzhih** [comment]
看看端口是否被占用

**Comment by icksky** [comment]
@xzhih 不好意思，现在才回复。80端口被httpd占用。但是报错情况看 应该不是端口吧。我记得nginx这边是81端口啊。报错的信息就是我提问的那个。网上是说没有这个用户跟用户组。但是我登录用户就是admin 我查看了 passwd跟group也有admin。。。

**Comment by xzhih** [comment]
不知道你是梅林哪个版本，我记得梅林好像在固件里面加了 www 用户和用户组，你可以试试 www www
