### ISSUE TITLE
脚本全部运行正常无报错，可是打开网页提示No input file specified

### ISSUE THREAD

**Issue by monlor** [xzhih/ONMP#21]
如题，我怀疑时php或者nginx配置问题。加入html文件可以打开，php文件打不开，mysql可以启动。

**Comment by xzhih** [comment]
什么固件，安装时有什么错误提示，查看 php 进程是否启动，另外检查目录权限

**Comment by monlor** [comment]
感谢🙏回复，我卸载onmp重装之后好了。
