### ISSUE TITLE
斐讯K3刷的tb梅林，启动失败

### ISSUE THREAD

**Issue by lovemay3** [xzhih/ONMP#22]
nginx 启动失败
php-fpm 启动失败
mysqld 启动失败
onmp启动失败

哪里能看到日志吗？
虚拟内存也开了，1g 的虚拟内存

安装的时候
Unknown package 'php7-mod-mcrypt'.
Collected errors:
 * opkg_install_cmd: Cannot install package php7-mod-mcrypt.

有这个错误，其它的都正常

**Comment by xzhih** [comment]
K3用原厂固件可以，梅林的话似乎无法获取到用户名，所以启动不了，要自己改脚本或者改配置
