### ISSUE TITLE
可以修改一下脚本， 添加redis的支持

### ISSUE THREAD

**Issue by darkrain88** [xzhih/ONMP#25]
php7-pecl-redis 

使用nextcloud 需要。

谢谢

**Comment by darkrain88** [comment]
连夜赶的程序？ 太厉害了。

entware的源要bin开头的， pkg 开头的里面没有redis，也封存了。

**Comment by xzhih** [comment]
安装命令里不是有更新脚本的选项嘛

**Comment by darkrain88** [comment]
谢谢
