### ISSUE TITLE
梅林entware中安装好了onmp，但是启动失败

### ISSUE THREAD

**Issue by ZhenShaw** [xzhih/ONMP#3]
onmp正在启动
nginx 启动成功
php-fpm 启动失败
mysqld 启动失败
onmp启动失败

要怎么解决

**Comment by xzhih** [comment]
我这边没有梅林固件的设备，所以环境不太了解
你可以尝试手动启动他们
启动PHP：`php-fpm  --fpm-config /opt/etc/php7-fpm.conf`
启动MySQL：`mysqld`
如果启动不成功，会看到报错，更多的log在：`/opt/var/log/`

没办法解决的话，可以加qq群：`346477750`，
我有时间可以帮你看看，顺便可以适配一下梅林

**Comment by xzhih** [comment]
我刚才找了一个梅林的机器测试了，开启swap（onmp open，选7）就能启动了，建议开启之后进行一次全部重置（onmp open，选5），之后就能玩爽了
