### ISSUE TITLE
能不能适配一下新的nextcloud 14

### ISSUE THREAD

**Issue by darkrain88** [xzhih/ONMP#30]
死活都登陆不了 内部错误

nc14在lib private token authority 目录下面 添加很多文件。

还要配置openssl的目录，但是也不能登陆。

op 上面的openssl 是不是不配套？

求帮忙适配一下。

**Comment by darkrain88** [comment]
@xzhih 谢谢 关键14好像op上面搞不定

登陆配置新的认证key 

多了很多文件

14需要php至少512内存了

**Comment by darkrain88** [comment]
还有方便添加一下phpmyadmin的tmp目录 

运行时 会提醒 没有tmp目录

还有个想法：能不能加个国际版， 哈哈。

**Comment by xzhih** [comment]
1. nextcloud 14 对性能要求更加高了，要是跑不动也没办法
2. 我刚刚把 phpmyadmin 的 tmp 添加了
3. 什么国际版？英文版是吗？
4. 问一下，你用什么设备跑的 onmp

**Comment by darkrain88** [comment]
@xzhih

- ~~~~ 是的英文版。 

- ~~~~ 我是软路由上面跑的 j1900比较垃圾的cpu

但是跑是没有问题。

14的确搞不定 我已经退回13.0.6了

**Comment by xzhih** [comment]
这脚本没啥人用的，没啥场景，英文版也没卵用

**Comment by darkrain88** [comment]
@xzhih 哈哈 还是不错的 至少里面几个软件 都研究过 要不然怎么会配置呢。
