### ISSUE TITLE
13.0.7 new config required

### ISSUE THREAD

**Issue by darkrain88** [xzhih/ONMP#32]
Security & setup warnings
It's important for the security and performance of your instance that everything is configured correctly. To help you with that we are doing some automatic checks. Please see the Tips & Tricks section and the documentation for more information.

```
Your web server is not properly set up to resolve "/.well-known/caldav". Further information can be found in the documentation.
Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the documentation.
```
Please double check the installation guides ↗, and check for any errors or warnings in the log.

**Comment by xzhih** [comment]
不能用就别更新，没啥意思

**Comment by darkrain88** [comment]
哈哈 直接删掉前面那个就好了
