### ISSUE TITLE
pkglist列表中的mariadb-server-extra mariadb-client貌似找不到

### ISSUE THREAD

**Issue by lovemay3** [xzhih/ONMP#33]
一个多月前用的，发现pkglist里的mariadb-server-extra mariadb-client一直无法安装，删掉之后整个脚本才正常运行。

**Comment by xzhih** [comment]
怎么可能没有，http://bin.entware.net/ 在这里面，自己看，你没换到 entware 源就没有，没换源用不了 onmp 的

**Comment by lovemay3** [comment]
哦哦，我没换源，只是删了mariadb-server-extra mariadb-client，正常使用了
