### ISSUE TITLE
补充如果出现unexpected operator或者not found等错误可以试一试以下方法

### ISSUE THREAD

**Issue by samondlee** [xzhih/ONMP#35]
https://blog.csdn.net/lincyang/article/details/39268135

原因应该是在ubuntu中默认的脚本语言是dash，用sh运行会采用dash的语言规则，所以会有如此错误。
如果用“./xxx.sh”来运行就没有问题了。那么咱们必须要用sh加参数来调试我们的脚本，怎么办？

好办，只需做一下配置修改就可以了。将使用dash 作为默认的系统脚本的选项取消掉。

命令为：

sudo dpkg-reconfigure dash

此时会跳到下面的配置页面，选择no并回车就好了。

**Comment by xzhih** [comment]
这脚本和 Ubuntu 有个啥关系。。。

**Comment by wawcff** [comment]
> 这脚本和 Ubuntu 有个啥关系。。。

emmm我在N1 装debian 上用这个脚本就出现了这个问题，

然后 这样修改之后就不报错了。。。。

我在另一个X86 CENTOS上也用的你这个脚本哈哈哈哈

**Comment by xzhih** [comment]
这些 Linux 发行版可以用其它更好的面板啊，没必要用这个

**Comment by wawcff** [comment]
> 这些 Linux 发行版可以用其它更好的面板啊，没必要用这个

不知道为啥 lnmp 在 N1 的 debian 上始终安不上。。。hhhh

X86不想用宝塔

**Comment by xzhih** [comment]
X86 有相当多的选择，所以我也没想到有人用这个，N1 装不上 lnmp 应该是源的问题
