### ISSUE TITLE
Nextcloud安装有问题

### ISSUE THREAD

**Issue by heartnn** [xzhih/ONMP#4]
Nextcloud只能打开安装界面，填完数据库后也可以正确生成数据表，但是无法打开，nginx 500错误，估计是nginx的配置文件有问题，owncloud可以正确安装，也可以打开，但是上传文件大小被限制在10K？似乎是，大概看了一下php设置，似乎没有问题
是不是路由器性能问题？我的ac68u，梅林

**Comment by xzhih** [comment]
Nextcloud目前只在软路由上跑得流畅，硬路由就别用它了，上传不了大文件是临时目录的权限问题，chmod -R 777 /opt/tmp 即可解决

**Comment by heartnn** [comment]
了解，多谢回复
