### ISSUE TITLE
wordpress configuration

### ISSUE THREAD

**Issue by jack338c** [xzhih/ONMP#42]
Dear 
Here are my steps:

open 192.168.x.1:83 ,then fill DB_NAME"wp" ,DB_USER"root" ,hostname"localhost" table prefix"_wp" and passwd,but it's failed

then I change the way
cp wp-config-sample.php wp-config.php in /opt/wwwroot/WordPress
then fill the DB_NAME ,DB_USER and password data  which configurated by phpMyaAdmin previously to wp-config.php 
but I still can't open 192.168.x.1:83,it shows wrong connections

Could you tell me the right steps ?
many thanks

**Comment by xzhih** [comment]
First, determine if MySQL is installed correctly, then use phpmyadmin to create a WordPress database and enter information based on the installation prompts.

**Comment by jack338c** [comment]
Hi,thanks for your response
it works now !
You great :+1:

**Comment by jack338c** [comment]
one more question: how to access wordpress from outside ?

I can access between Nextclould and wordpress by 192.168.1.1: 99 and 192.168.1.1: 83 from internel network

then I port forward 99 to externel port 2000  port forward 83 to externel port 3000 

Now I can open Nextclould (port 2000) from outside(Dynamic DNS on openwrt),but wordpress not

thanks

**Comment by xzhih** [comment]
You may need to open firewall port 3000.

**Comment by jack338c** [comment]
I don't understand whatever I assigned port 3000,4000 or 1000
It will return to xxx.cn:83 suddenly while opening xxx.cn:3000 or xxx.cn:4000,xxx.cn:1000
I'm confused 😖

**Comment by xzhih** [comment]
Oh, I get it now. 
You need to set it up in WordPress, 
because when you install WordPress, xxx.cn:83 is set by default.

**Comment by xzhih** [comment]
Or map internal port 83 to external port 83.

**Comment by jack338c** [comment]
It works again ! 😄 
I owe you one ,thanks a lot!

**Comment by xzhih** [comment]
Why don't you speak Chinese?

**Comment by jack338c** [comment]
好的，下次我就用中文提问
谢谢了 :smiley:
