### ISSUE TITLE
大良哥能研究一下Entware上的seafile吗？

### ISSUE THREAD

**Issue by ouchyoung** [xzhih/ONMP#8]
我看见entware在armv7的库里有seafile的包，但是装上了跑不起来。经过多方折腾，找到缺了几个python的依赖库，现在发现的是缺futures, requests，另外还缺pgrep程序（默认没有作为依赖包进行安装）。pillow的版本有点低，库里也没有python-imaging。把这些玩意装上了，把pillow的新版编译装上了，程序能启动，但是从客户端访问的时候，报500 internal server error的错误。研究了一个月，还是没招。

和ONMP脚本里预设的owncloud与nextcloud比起来，seafile在处理大批量小文件同步的时候具有很强的优势。前面两个基于PHP，后面一个基于C，所以可能在同步功能上，更专业一些。

请大良哥费费心吧！谢谢~

**Comment by xzhih** [comment]
路由器跑 seafile 的压力是真的大，很容易把路由器搞宕机了，另外你所说的 ‘基于C’，表达不准确。

大家可能都觉得 seafile 是比 NC 、OC 专业，都想用，奈何跑不动啊

**Comment by ouchyoung** [comment]
seafile确实是用C语言编写的啊
![image](https://user-images.githubusercontent.com/9261358/38969727-4b24ad5a-43c4-11e8-9df7-2fa454def514.png)
话说，owncloud跑同步的时候，负荷也不低哦。但是这个路由器能吃下来的。

**Comment by xzhih** [comment]
他的服务器版本的内核是C写的，整个程序不全是C写的，要全是，那就很容易在路由器运行了

树莓派CPU的MFLOPS比路由器强很多，并且这个能不能运行确实要看平台，毕竟很多软件都没有给mipsel（目前大多数路由器）这个平台编译好软件，都是民间的人编译的，能不能运行看运气啦

OC，NC在路由器上用的体验也不行，我早已放弃使用

**Comment by ouchyoung** [comment]
好的，非常感谢！那我也就放弃了
